spring:
  application:
    name: MedXpress
  profiles:
    active: local   # default profile; override with SPRING_PROFILES_ACTIVE

server:
  port: 8080

logging:
  level:
    root: INFO

app:
  jwt:
    secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
    expiration-minutes: 120
