spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medxpress_db
    username: lino
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/changelog-dev.yaml

logging:
  level:
    liquibase: DEBUG

server:
  port: 8080
